### ISSUE TITLE
Firebase DB

### ISSUE THREAD

**Issue by gratsal** [AntonMMRTS/FoodDeliveryApp#34]
Can you share a print screen of firestore database to understand the actual structure of it? when I run the project no products are shown. Thanks. good job.

**Comment by AntonMMRTS** [comment]
Hello, yes, sure. Hope it helps you.
<img width="1280" alt="Снимок экрана 2021-10-01 в 08 09 23" src="https://user-images.githubusercontent.com/79893831/135552263-5e633484-25e3-467f-9829-4b49c28f6ea1.png">

**Comment by AntonMMRTS** [comment]
<img width="1280" alt="Снимок экрана 2021-10-01 в 08 13 48" src="https://user-images.githubusercontent.com/79893831/135552343-94be93cd-7751-4d69-8520-98aa6f9c4a99.png"
<img width="1291" alt="Снимок экрана 2021-10-01 в 08 13 28" src="https://user-images.githubusercontent.com/79893831/135552354-3eb1f72b-95f0-4100-bf39-475cea7f320d.png">
>

**Comment by AntonMMRTS** [comment]
<img width="1280" alt="Снимок экрана 2021-10-01 в 08 13 48" src="https://user-images.githubusercontent.com/79893831/135552492-de29c2f2-9cc3-439b-8e64-e62d3cae3f5d.png">

**Comment by gratsal** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2021-10-01 at 21 46 27](https://user-images.githubusercontent.com/10564812/135671585-18df729b-9dca-40d1-bf19-7e3b2187623c.png)

Thank you for your help Sir
I have Auth with mobile correctly and setup database like you did but I get this
